name: Puff_chatbot
description: a chat bot that can assists you

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:

    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  flutter_spinkit: ^5.2.0
  dio: ^5.3.3
  animated_text_kit: ^4.2.2
  awesome_dialog: ^3.1.0
  http: ^1.2.2
  flutter_gemini: ^2.0.5
  google_generative_ai: 0.4.6
  dash_chat_2: ^0.0.21

dev_dependencies:
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/ai-buddy-logo-3DB2A531D8-seeklogo.com.png"

flutter:
  uses-material-design: true

  assets:
      - assets/images/ai-buddy-logo-3DB2A531D8-seeklogo.com.png

